const S={users:'wln_v4_users',session:'wln_v4_session',progress:'wln_v4_progress',rooms:'wln_v4_rooms',messages:'wln_v4_messages',forum:'wln_v4_forum',tickets:'wln_v4_tickets'};
let st={auth:'login',view:'dashboard',week:1,tab:'overview',mentor:'semar',room:null,session:null};
const $=q=>document.querySelector(q), app=()=>$('#app'), modal=()=>$('#modalRoot');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const users=()=>get(S.users,[]), saveUsers=u=>set(S.users,u), rooms=()=>{let r=get(S.rooms,null); if(!r){set(S.rooms,DEFAULT_ROOMS); return DEFAULT_ROOMS} return r}, saveRooms=r=>set(S.rooms,r);
const uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase();
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2800)}
function init(){st.session=get(S.session,null); render(); if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations?.().then(rs=>rs.forEach(r=>r.unregister()))}}
function render(){if(!st.session)return auth(); shell()}
function auth(){app().innerHTML=`<main class="wln-auth"><section class="auth-left"><img src="assets/logo-5d.png" class="auth-logo"><div class="auth-kicker">AI-powered Wayang storytelling for EFL skills</div><h1 class="auth-title">Wayang <span>Lingua</span><br>Nusantara</h1><p class="auth-copy">Protected learning environment. Users must register or login before accessing materials, dashboards, rooms, AI tutors, assessments, and reports.</p><div class="auth-stats"><div class="stat-card"><b>16</b><span>weekly meetings</span></div><div class="stat-card"><b>10</b><span>AI Wayang tutors</span></div><div class="stat-card"><b>4</b><span>online rooms</span></div><div class="stat-card"><b>3</b><span>role dashboards</span></div></div></section><section class="auth-right"><div class="auth-card"><div class="row" style="justify-content:space-between"><img src="assets/emblem-5d.png" style="width:66px;height:66px;object-fit:contain"><span class="pill">Protected Access</span></div><h2>Enter the App</h2><p class="muted">Student and lecturer accounts must be registered. Admin uses official PIN.</p><div class="auth-tabs"><button class="${st.auth==='login'?'active':''}" onclick="st.auth='login';render()">Login</button><button class="${st.auth==='register'?'active':''}" onclick="st.auth='register';render()">Register</button><button class="${st.auth==='admin'?'active':''}" onclick="st.auth='admin';render()">Admin PIN</button></div>${authForm()}<div class="auth-note"><b>Copyright © Dr. Joko Slamet</b><br>Ready-use materials and live interactive features open only after login.</div></div></section></main>`}
function authForm(){if(st.auth==='register')return`<form class="form-grid" onsubmit="registerUser(event)"><div class="grid-2"><div class="input-group"><label>Full Name</label><input name="name" required></div><div class="input-group"><label>Role</label><select name="role"><option value="student">Student</option><option value="lecturer">Lecturer</option></select></div></div><div class="input-group"><label>Email</label><input name="email" type="email" required></div><div class="grid-2"><div class="input-group"><label>Password</label><input name="password" type="password" minlength="4" required></div><div class="input-group"><label>Class / Institution</label><input name="institution" required></div></div><button class="btn primary full">Create Account</button></form>`; if(st.auth==='admin')return`<form class="form-grid" onsubmit="adminLogin(event)"><div class="input-group"><label>Admin PIN</label><input name="pin" type="password" required placeholder="Enter PIN"></div><button class="btn primary full">Access Admin Dashboard</button></form>`; return`<form class="form-grid" onsubmit="loginUser(event)"><div class="input-group"><label>Email</label><input name="email" type="email" required></div><div class="input-group"><label>Password</label><input name="password" type="password" required></div><button class="btn primary full">Login</button><button class="btn ghost full" type="button" onclick="st.auth='register';render()">New user? Create account</button></form>`}
function registerUser(e){e.preventDefault();let f=new FormData(e.target), email=f.get('email').toLowerCase().trim(), us=users(); if(us.some(u=>u.email===email))return toast('Email already registered.'); let u={id:uid('USER'),name:f.get('name'),role:f.get('role'),email,password:f.get('password'),institution:f.get('institution'),phone:'',bio:'',cefrTarget:'B1',photo:'',createdAt:new Date().toISOString()};us.push(u);saveUsers(us); loginAs(u)}
function loginUser(e){e.preventDefault();let f=new FormData(e.target), u=users().find(x=>x.email===f.get('email').toLowerCase().trim()&&x.password===f.get('password')); if(!u)return toast('Login failed. Please check account.'); loginAs(u)}
function adminLogin(e){e.preventDefault();if(new FormData(e.target).get('pin')!=='JS2026')return toast('Incorrect admin PIN.'); loginAs({id:'ADMIN-JS2026',name:'Dr. Joko Slamet Admin',role:'admin',email:'admin@wayanglingua.local',institution:'Wayang Lingua Nusantara',photo:'',cefrTarget:'C2',bio:'System administrator'})}
function loginAs(u){let s={...u};delete s.password; st.session=s; set(S.session,s); toast('Welcome '+s.name); render()}
function logout(){localStorage.removeItem(S.session);st.session=null;render()}
const initials=n=>(n||'WL').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
function avatar(u=st.session){return u?.photo?`<img class="avatar" src="${u.photo}">`:`<div class="avatar">${esc(initials(u?.name))}</div>`}
const roleName=r=>r==='admin'?'Administrator':r==='lecturer'?'Lecturer':'Student';
function nav(){let r=st.session.role;let base=r==='admin'?[['dashboard','Admin Dashboard','⌂'],['users','Users','👥'],['materials','Materials Manager','▣'],['rooms','Online Rooms','◉'],['reports','Reports','▤'],['profile','Profile','☻']]:r==='lecturer'?[['dashboard','Lecturer Dashboard','⌂'],['classes','Classes','👥'],['materials','Teaching Materials','▣'],['assessment','Assessments','✓'],['rooms','Online Rooms','◉'],['mentor','AI Tutors','✦'],['reports','Reports','▤'],['profile','Profile','☻']]:[['dashboard','Student Dashboard','⌂'],['world','Wayang World','✦'],['materials','Learning Modules','▣'],['mentor','AI Tutors','✦'],['rooms','Online Rooms','◉'],['portfolio','Portfolio','★'],['reports','Reports','▤'],['profile','Profile','☻']];return base}
function shell(){let u=st.session;app().innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="side-brand"><img src="assets/emblem-5d.png"><div><h1>Wayang<br>Lingua<br>Nusantara</h1><p>EFL · Culture · AI Mentor</p></div></div><div class="profile-mini side-card">${avatar(u)}<div><b>${esc(u.name)}</b><br><span class="small">${roleName(u.role)} · ${esc(u.institution||'Community')}</span></div></div><div class="side-section">Navigation</div><nav class="nav-list">${nav().map(n=>`<button class="nav-item ${st.view===n[0]?'active':''}" onclick="go('${n[0]}')"><span>${n[2]}</span>${n[1]}</button>`).join('')}</nav><div class="side-card"><b>Copyright © Dr. Joko Slamet</b><p class="small">Complete protected app. Admin PIN: JS2026.</p></div></aside><main class="main"><header class="topbar"><div class="top-title"><img src="assets/logo-5d.png"><div><h2>${title()}</h2><p>${roleName(u.role)} workspace</p></div></div><div class="top-actions"><button class="btn" onclick="openChat()">💬 Chat</button><button class="btn" onclick="openForum()">🗣️ Forum</button><button class="btn" onclick="openHelpDesk()">🛟 Help Desk</button><button class="btn ghost" onclick="go('profile')">Profile</button><button class="btn danger" onclick="logout()">Logout</button></div></header><section class="content">${view()}</section><footer class="footer">Wayang Lingua Nusantara · Copyright © Dr. Joko Slamet</footer></main></div>`}
function go(v){st.view=v;render()}function title(){return ({dashboard:'Dashboard',world:'Wayang World',materials:'16-Week Materials',mentor:'AI Wayang Tutors',rooms:'Online Room Center',portfolio:'Portfolio',reports:'Reports',profile:'Editable Profile',users:'User Management',classes:'Classes',assessment:'Assessments'}[st.view]||'Wayang Lingua Nusantara')}
function view(){return st.view==='dashboard'?dashboard():st.view==='world'?world():st.view==='materials'?materials():st.view==='mentor'?mentor():st.view==='rooms'?roomsPage():st.view==='portfolio'?portfolio():st.view==='reports'?reports():st.view==='profile'?profile():st.view==='users'?usersPage():st.view==='classes'?classesPage():st.view==='assessment'?assessmentPage():dashboard()}
function progress(email=st.session.email){let all=get(S.progress,{});return all[email]||{completed:[],quiz:{},speaking:{},writing:{},portfolio:[]}}function saveProgress(p,email=st.session.email){let all=get(S.progress,{});all[email]=p;set(S.progress,all)}
function hero(h,p){return`<div class="hero-panel"><div><div class="auth-kicker">Rooted in Heritage · Designed for Learning · Built for the World</div><h1>${h}</h1><p>${p}</p><div class="feature-tiles"><div class="tile"><b>16</b><span>complete meetings</span></div><div class="tile"><b>10</b><span>AI tutors</span></div><div class="tile"><b>4</b><span>online rooms</span></div><div class="tile"><b>∞</b><span>export data</span></div></div></div><div class="card"><img src="assets/stage-hero.png" style="width:100%;border-radius:18px;border:1px solid var(--line)"><div class="badge-row" style="margin-top:12px"><span class="pill">Listening</span><span class="pill">Speaking</span><span class="pill">Reading</span><span class="pill">Writing</span></div></div></div>`}
function pct(x){return Math.min(100,20+progress().completed.length*5+x*4)}function metric(l,v,p){return`<div class="metric"><div><b>${l}</b><div class="small">${v}</div></div><div style="width:48%"><div class="progress"><span style="width:${Math.max(5,Math.min(100,p))}%"></span></div></div></div>`}
function dashStats(){return metric('Listening',pct(2)+'%',pct(2))+metric('Speaking',pct(3)+'%',pct(3))+metric('Reading',pct(4)+'%',pct(4))+metric('Writing',pct(1)+'%',pct(1))+metric('Culture',pct(5)+'%',pct(5))}
function dashboard(){let r=st.session.role,p=progress(),next=MODULES.find(m=>!p.completed.includes(m.week))||MODULES[15];if(r==='admin')return hero('Admin <span>Console</span>','Control users, materials, rooms, and reports.')+`<div class="panel-grid"><div class="card span-3"><h3>Users</h3><div class="tile"><b>${users().length}</b><span>registered</span></div></div><div class="card span-3"><h3>Materials</h3><div class="tile"><b>16</b><span>meetings</span></div></div><div class="card span-3"><h3>Rooms</h3><div class="tile"><b>${rooms().length}</b><span>available</span></div></div><div class="card span-3"><h3>Exports</h3><button class="btn primary full" onclick="exportAll()">Export All Data</button></div><div class="card span-12"><h3>Users</h3>${usersTable()}</div></div>`; if(r==='lecturer')return hero('Lecturer <span>Dashboard</span>','Teach with culture, assess with confidence, and export class evidence.')+`<div class="panel-grid"><div class="card span-4"><h3>Class Summary</h3>${classStats()}</div><div class="card span-4"><h3>Teaching Actions</h3><button class="btn primary full" onclick="go('materials')">Open Materials</button><button class="btn full" onclick="go('assessment')">Assessments</button><button class="btn full" onclick="go('rooms')">Room Center</button></div><div class="card span-4"><h3>Student Progress</h3>${classTable()}</div></div>`;return hero(`Welcome, <span>${esc(st.session.name.split(' ')[0])}</span>`,`Continue Week ${next.week}: ${next.title}.`)+`<div class="panel-grid"><div class="card span-4"><h3>Progress</h3>${metric('Completed',p.completed.length+'/16',p.completed.length/16*100)}${dashStats()}<button class="btn primary full" onclick="openModule(${next.week})">Continue Week ${next.week}</button></div><div class="card span-4"><h3>Today’s Mission</h3><p><b>${next.title}</b></p><p class="muted">${next.summary}</p>${next.vocabulary.slice(0,5).map(v=>`<span class="vocab">${v}</span>`).join('')}</div><div class="card span-4"><h3>Quick Access</h3><button class="btn full" onclick="go('mentor')">AI Tutors</button><button class="btn full" onclick="go('rooms')">Online Room</button><button class="btn full" onclick="go('reports')">My Report</button></div></div>`}
function classStats(){let ss=users().filter(u=>u.role==='student'),avg=ss.length?Math.round(ss.reduce((a,u)=>a+progress(u.email).completed.length,0)/ss.length/16*100):0;return metric('Registered students',ss.length,ss.length*10)+metric('Average completion',avg+'%',avg)+metric('Ready modules','16/16',100)}
function classTable(){let ss=users().filter(u=>u.role==='student'); if(!ss.length)return'<p class="muted">No student registered yet.</p>';return`<div class="table-wrap"><table><tr><th>Student</th><th>Email</th><th>Completed</th><th>CEFR</th></tr>${ss.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${progress(u.email).completed.length}/16</td><td>${esc(u.cefrTarget||'B1')}</td></tr>`).join('')}</table></div>`}
function usersTable(){let us=users(); if(!us.length)return'<p class="muted">No registered users yet.</p>';return`<div class="table-wrap"><table><tr><th>Name</th><th>Role</th><th>Email</th><th>Institution</th><th>Action</th></tr>${us.map(u=>`<tr><td>${esc(u.name)}</td><td>${u.role}</td><td>${esc(u.email)}</td><td>${esc(u.institution)}</td><td><button class="btn danger" onclick="deleteUser('${u.id}')">Delete</button></td></tr>`).join('')}</table></div>`}
function deleteUser(id){if(!confirm('Delete this user?'))return;saveUsers(users().filter(u=>u.id!==id));render()}
function world(){return`<div class="panel-grid"><div class="card span-12"><h3>Wayang World Character Library</h3><p class="muted">All characters are integrated as AI-style tutors, roleplay guides, and cultural mentors.</p></div>${MENTORS.map(m=>`<div class="mentor-card span-3"><img src="${m.img}"><h3>${m.name}</h3><b class="gold">${m.role}</b><p class="muted">${m.focus}</p><button class="btn primary full" onclick="st.mentor='${m.id}';go('mentor')">Practice</button></div>`).join('')}</div>`}
function materials(){let m=MODULES.find(x=>x.week===st.week)||MODULES[0];return`<div class="panel-grid"><div class="card span-4"><h3>16-Week Materials</h3><div class="module-list">${MODULES.map(x=>`<button class="module-card ${x.week===st.week?'active':''}" onclick="openModule(${x.week})"><span class="week-badge">${x.week}</span><span><b>${x.title}</b><br><span class="small">${x.level} · ${x.focus}</span></span><span class="pill">${x.level}</span></button>`).join('')}</div></div><div class="module-detail span-8"><h3>Week ${m.week}: ${m.title}</h3><p class="muted">${m.summary}</p><div class="module-tabs">${['overview','listen','read','speak','write','quiz','assessment'].map(t=>`<button class="${st.tab===t?'active':''}" onclick="st.tab='${t}';render()">${t}</button>`).join('')}</div>${moduleTab(m)}</div></div>`}
function openModule(w){st.week=w;st.view='materials';st.tab='overview';render()}
function moduleTab(m){if(st.tab==='listen')return`<h4>Listening Script</h4><p>${m.listeningScript}</p><button class="btn primary" onclick="speakText(\`${m.listeningScript.replace(/`/g,'')}\`)">Play Narration</button><button class="btn" onclick="stopSpeak()">Stop</button>`; if(st.tab==='read')return`<h4>Reading Text</h4><p>${m.reading}</p><h4>Vocabulary</h4>${m.vocabulary.map(v=>`<span class="vocab">${v}</span>`).join('')}`; if(st.tab==='speak')return`<h4>Speaking Performance</h4><p>${m.speakingPrompt}</p><p>${m.roleplayPrompt}</p><textarea id="speakInput" placeholder="Paste or type your spoken response here. You can also use Start Recording if supported."></textarea><div class="row"><button class="btn primary" onclick="startSpeech()">Start Recording</button><button class="btn" onclick="mentorFeedback('dalang','speakInput','speakOut')">Get Dalang Feedback</button></div><div id="speakOut" class="card" style="margin-top:12px"></div>`; if(st.tab==='write')return`<h4>Writing Studio</h4><p>${m.writingTask}</p><textarea id="writeInput" placeholder="Write your paragraph here..."></textarea><div class="row"><button class="btn primary" onclick="mentorFeedback('gareng','writeInput','writeOut')">Analyze Writing</button><button class="btn" onclick="saveWriting()">Save to Portfolio</button></div><div id="writeOut" class="card" style="margin-top:12px"></div>`; if(st.tab==='quiz')return quizHTML(m); if(st.tab==='assessment')return`<h4>Assessment Package</h4><ul><li>${m.assessment.quiz}</li><li>${m.assessment.speaking}</li><li>${m.assessment.writing}</li><li>${m.assessment.portfolio}</li></ul><h4>Rubric</h4><div class="table-wrap"><table><tr><th>Criterion</th><th>Max Score</th></tr>${m.rubric.map(r=>`<tr><td>${r.criterion}</td><td>${r.max}</td></tr>`).join('')}</table></div><button class="btn primary" onclick="completeWeek(${m.week})">Mark Week ${m.week} Complete</button>`;return`<h4>Objectives</h4><ul>${m.objectives.map(o=>`<li>${o}</li>`).join('')}</ul><p><b>Grammar / Language Focus:</b> ${m.grammar}</p><p><b>Core Character:</b> ${m.character}</p><div class="badge-row">${m.vocabulary.map(v=>`<span class="vocab">${v}</span>`).join('')}</div>`}
function quizHTML(m){return`<form onsubmit="submitQuiz(event,${m.week})">${m.quiz.map((q,i)=>`<div class="card"><b>${i+1}. ${q.q}</b>${q.options.map((o,j)=>`<label class="quiz-option"><input type="radio" name="q${i}" value="${j}" required> ${o}</label>`).join('')}</div>`).join('')}<button class="btn primary">Submit Quiz</button></form>`}
function submitQuiz(e,w){e.preventDefault();let m=MODULES.find(x=>x.week===w),fd=new FormData(e.target),score=0;m.quiz.forEach((q,i)=>{if(Number(fd.get('q'+i))===q.answer)score++});let p=progress();p.quiz[w]=score*20; if(score>=3&&!p.completed.includes(w))p.completed.push(w);saveProgress(p);toast('Quiz score: '+score+'/5');render()}
function completeWeek(w){let p=progress();if(!p.completed.includes(w))p.completed.push(w);saveProgress(p);toast('Week '+w+' completed.');render()}
function saveWriting(){let txt=$('#writeInput')?.value||'';if(!txt.trim())return toast('Write first.');let p=progress();p.writing[st.week]=txt;p.portfolio.push({type:'writing',week:st.week,date:new Date().toLocaleString(),text:txt});saveProgress(p);toast('Saved to portfolio')}
function speakText(t){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}function stopSpeak(){speechSynthesis.cancel()}
function startSpeech(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Speech recognition is not supported in this browser. Type your response instead.');let r=new R();r.lang='en-US';r.onresult=e=>{$('#speakInput').value=[...e.results].map(x=>x[0].transcript).join(' ')};r.start()}
function mentor(){let m=MENTORS.find(x=>x.id===st.mentor)||MENTORS[0];return`<div class="panel-grid"><div class="card span-4"><h3>All AI Wayang Tutors</h3><div class="mentor-grid">${MENTORS.map(x=>`<button class="mentor-card" onclick="st.mentor='${x.id}';render()"><img src="${x.img}"><b>${x.name}</b><br><span class="small">${x.role}</span></button>`).join('')}</div></div><div class="card span-8"><h3>${m.name} · ${m.role}</h3><p class="muted">Focus: ${m.focus}</p><textarea id="mentorText" placeholder="Type speaking script, writing draft, vocabulary sentence, or cultural explanation..."></textarea><div class="row"><button class="btn primary" onclick="mentorFeedback('${m.id}','mentorText','mentorOut')">Run ${m.name}</button><button class="btn" onclick="$('#mentorText').value=MODULES[st.week-1].writingTask">Use Current Task</button></div><div id="mentorOut" class="card" style="margin-top:12px"></div></div></div>`}
function mentorFeedback(id,input,out){let t=$('#'+input)?.value||'';if(!t.trim())return toast('Please type your text first.');let words=t.trim().split(/\s+/).length, sent=(t.match(/[.!?]/g)||[]).length||1, score=Math.min(96,50+Math.floor(words/4)+(sent>1?8:0));let name=(MENTORS.find(m=>m.id===id)||MENTORS[0]).name;let notes=[`Estimated score: ${score}/100`,`Words: ${words}; sentences: ${sent}`, id==='gareng'?'Check verb tense, articles, and sentence boundaries.':id==='petruk'?'Practice stress, final sounds, and intonation rise/fall.':id==='bagong'?'Add richer collocations and academic vocabulary.':id==='dalang'?'Improve audience opening, emotion, and storytelling flow.':'Clarify moral meaning and connect it to real learning.'];$('#'+out).innerHTML=`<h4>${name} Feedback</h4><ul>${notes.map(n=>`<li>${n}</li>`).join('')}</ul>`}
function roomsPage(){if(st.room)return roomStage();let r=rooms();return`<div class="card"><h3>Online Room Center</h3><p class="muted">Available rooms are pre-integrated. Admin or lecturer can edit meeting links.</p></div><div class="room-grid" style="margin-top:16px">${r.map(x=>`<div class="room-card"><span class="room-live">${x.status}</span><h3>${x.name}</h3><p class="muted">${x.purpose}</p><p><b>Schedule:</b> ${x.schedule}<br><b>Host:</b> ${x.host}<br><b>Capacity:</b> ${x.capacity}</p><button class="btn primary" onclick="joinRoom('${x.id}')">Join Room</button> ${st.session.role!=='student'?`<button class="btn" onclick="editRoom('${x.id}')">Edit</button>`:''}</div>`).join('')}</div>`}
function joinRoom(id){st.room=id;render()}function roomStage(){let r=rooms().find(x=>x.id===st.room);return`<button class="btn" onclick="st.room=null;render()">← Back to Rooms</button><div class="room-stage" style="margin-top:16px"><div class="video-box"><div><h2>${r.name}</h2><p>${r.purpose}</p><div class="video-controls"><button class="btn primary" onclick="window.open('${r.link}','_blank')">Open Meeting Link</button><button class="btn" onclick="toast('Microphone toggled')">🎙️ Mic</button><button class="btn" onclick="toast('Camera toggled')">📷 Camera</button><button class="btn" onclick="toast('Screen share prepared')">🖥️ Share</button></div></div></div><div class="card chat-box"><h3>Room Chat</h3><div id="roomChat" class="chat-stream">${roomMsgs(r.id).map(msg).join('')}</div><div class="row" style="margin-top:8px"><input id="roomMsg" placeholder="Type message"><button class="btn primary" onclick="sendRoomMsg('${r.id}')">Send</button></div></div></div>`}
function roomMsgs(id){return get(S.messages,{} )[id]||[]}function msg(m){return`<div class="msg"><b>${esc(m.name)}</b><br>${esc(m.text)}<div class="small">${m.date}</div></div>`}function sendRoomMsg(id){let inp=$('#roomMsg');if(!inp.value.trim())return;let all=get(S.messages,{});all[id]=all[id]||[];all[id].push({name:st.session.name,text:inp.value,date:new Date().toLocaleString()});set(S.messages,all);render()}
function editRoom(id){let r=rooms().find(x=>x.id===id);openModal('Edit Room',`<div class="form-grid"><input id="erName" value="${esc(r.name)}"><input id="erSchedule" value="${esc(r.schedule)}"><input id="erLink" value="${esc(r.link)}"><textarea id="erPurpose">${esc(r.purpose)}</textarea><button class="btn primary" onclick="saveRoom('${id}')">Save Room</button></div>`)}function saveRoom(id){let rs=rooms(),r=rs.find(x=>x.id===id);r.name=$('#erName').value;r.schedule=$('#erSchedule').value;r.link=$('#erLink').value;r.purpose=$('#erPurpose').value;saveRooms(rs);closeModal();render()}
function portfolio(){let p=progress();return`<div class="card"><h3>Performance Portfolio</h3><p class="muted">Evidence of quizzes, writing, speaking, and complete modules.</p>${metric('Completed modules',p.completed.length+'/16',p.completed.length/16*100)}<h4>Writing Evidence</h4>${Object.entries(p.writing).map(([w,t])=>`<div class="card"><b>Week ${w}</b><p>${esc(t)}</p></div>`).join('')||'<p class="muted">No portfolio evidence yet.</p>'}</div>`}
function reports(){let p=progress();return`<div class="panel-grid"><div class="card span-6"><h3>${roleName(st.session.role)} Report</h3>${metric('Completion',p.completed.length+'/16',p.completed.length/16*100)}${dashStats()}<button class="btn primary" onclick="exportReport('json')">Export JSON</button><button class="btn" onclick="exportReport('csv')">Export CSV</button><button class="btn" onclick="window.print()">Print</button></div><div class="report-paper span-6"><h2>Wayang Lingua Nusantara</h2><h3>Certificate / Learning Report</h3><p>This certifies that <b>${esc(st.session.name)}</b> has participated in the Wayang-based EFL learning program.</p><p>Completed meetings: <b>${p.completed.length}/16</b></p><p>Role: ${roleName(st.session.role)}</p><p class="muted">Copyright © Dr. Joko Slamet</p></div></div>`}
function exportReport(type){let data={user:st.session,progress:progress(),modules:MODULES,rooms:rooms()};let txt=type==='csv'?`Name,Role,Completed\n${st.session.name},${st.session.role},${progress().completed.length}/16`:JSON.stringify(data,null,2);download('wayang-lingua-report.'+type,txt)}function exportAll(){download('wayang-lingua-all-data.json',JSON.stringify({users:users(),progress:get(S.progress,{}),rooms:rooms(),forum:get(S.forum,[]),tickets:get(S.tickets,[])},null,2))}function download(n,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function profile(){let u=st.session;return`<div class="panel-grid"><div class="card span-4"><h3>Profile Photo</h3>${avatar(u)}<p class="muted">Upload and update your profile photo.</p><input type="file" accept="image/*" onchange="uploadPhoto(event)"></div><div class="card span-8"><h3>Edit Profile</h3><form class="form-grid" onsubmit="saveProfile(event)"><div class="grid-2"><div class="input-group"><label>Name</label><input name="name" value="${esc(u.name)}"></div><div class="input-group"><label>CEFR Target</label><select name="cefrTarget">${['A1','A2','B1','B2','C1','C2'].map(x=>`<option ${u.cefrTarget===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="grid-2"><div class="input-group"><label>Institution/Class</label><input name="institution" value="${esc(u.institution||'')}"></div><div class="input-group"><label>Phone</label><input name="phone" value="${esc(u.phone||'')}"></div></div><div class="input-group"><label>Bio / Research or Learning Interest</label><textarea name="bio">${esc(u.bio||'')}</textarea></div><button class="btn primary">Save Profile</button></form></div></div>`}
function uploadPhoto(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{st.session.photo=r.result;set(S.session,st.session);let us=users().map(u=>u.email===st.session.email?{...u,photo:r.result}:u);saveUsers(us);toast('Photo updated');render()};r.readAsDataURL(file)}
function saveProfile(e){e.preventDefault();let f=new FormData(e.target);['name','institution','phone','bio','cefrTarget'].forEach(k=>st.session[k]=f.get(k));set(S.session,st.session);saveUsers(users().map(u=>u.email===st.session.email?{...u,...st.session,password:u.password}:u));toast('Profile saved');render()}
function usersPage(){return`<div class="card"><h3>User Management</h3>${usersTable()}</div>`}function classesPage(){return`<div class="card"><h3>Classes</h3>${classTable()}</div>`}function assessmentPage(){return`<div class="card"><h3>Complete Assessment Blueprint</h3><p class="muted">Each week includes quiz, speaking, writing, and portfolio assessment.</p><div class="table-wrap"><table><tr><th>Week</th><th>CEFR</th><th>Assessment</th></tr>${MODULES.map(m=>`<tr><td>${m.week}. ${m.title}</td><td>${m.level}</td><td>${m.assessment.quiz}; ${m.assessment.speaking}; ${m.assessment.writing}</td></tr>`).join('')}</table></div></div>`}
function openModal(t,b){modal().innerHTML=`<div class="modal"><div class="modal-head"><h3>${t}</h3><button class="btn" onclick="closeModal()">Close</button></div>${b}</div>`}function closeModal(){modal().innerHTML=''}
function openChat(){openModal('Chat Center',`<div id="globalChat" class="chat-stream" style="height:260px">${roomMsgs('global').map(msg).join('')}</div><div class="row" style="margin-top:8px"><input id="globalMsg" placeholder="Type message"><button class="btn primary" onclick="let v=$('#globalMsg').value;if(v.trim()){let all=get(S.messages,{});all.global=all.global||[];all.global.push({name:st.session.name,text:v,date:new Date().toLocaleString()});set(S.messages,all);openChat()}">Send</button></div>`)}
function openForum(){let fs=get(S.forum,[]);openModal('Forum',`<div class="form-grid"><input id="forumTitle" placeholder="Forum topic"><textarea id="forumBody" placeholder="Write discussion"></textarea><button class="btn primary" onclick="let fs=get(S.forum,[]);fs.push({name:st.session.name,title:$('#forumTitle').value,body:$('#forumBody').value,date:new Date().toLocaleString()});set(S.forum,fs);openForum()">Post</button></div>${fs.map(f=>`<div class="card"><b>${esc(f.title)}</b><p>${esc(f.body)}</p><span class="small">${esc(f.name)} · ${f.date}</span></div>`).join('')}`)}
function openHelpDesk(){let ts=get(S.tickets,[]);openModal('Help Desk',`<div class="form-grid"><input id="ticketTitle" placeholder="Issue title"><textarea id="ticketBody" placeholder="Describe the problem"></textarea><button class="btn primary" onclick="let ts=get(S.tickets,[]);ts.push({id:uid('TICKET'),name:st.session.name,title:$('#ticketTitle').value,body:$('#ticketBody').value,status:'Open',date:new Date().toLocaleString()});set(S.tickets,ts);openHelpDesk()">Submit Ticket</button></div>${ts.map(t=>`<div class="card"><b>${esc(t.title)}</b><p>${esc(t.body)}</p><span class="pill">${t.status}</span> <span class="small">${esc(t.name)} · ${t.date}</span></div>`).join('')}`)}
window.addEventListener('DOMContentLoaded',init);
