require('dotenv').config();
const express=require('express'); const cors=require('cors'); const jwt=require('jsonwebtoken'); const bcrypt=require('bcryptjs'); const multer=require('multer'); const QRCode=require('qrcode'); const {v4:uuid}=require('uuid');
const app=express(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});
app.use(cors()); app.use(express.json({limit:'10mb'}));
const JWT_SECRET=process.env.JWT_SECRET||'dev_secret_change';
const db={users:[],materials:[],assessments:[],rooms:[],attendance:[],submissions:[],scores:[],aiLogs:[],certificates:[],reports:[],research:[]};
const roles=['ADMIN','LECTURER','STUDENT','RESEARCHER'];
function seed(){ if(db.users.length) return; const hash=bcrypt.hashSync('Admin@JS2026',10); db.users.push({id:uuid(),name:'Dr. Joko Slamet',email:'admin@wayanglingua.id',passwordHash:hash,role:'ADMIN',institution:'Wayang Lingua Nusantara',avatar:'/assets/wayang-dark.png',createdAt:new Date().toISOString()});
const weeks=['Origins of Wayang and Global English','Semar and Reflective Speaking','Gareng and Grammar Accuracy','Petruk and Pronunciation Rhythm','Bagong and Vocabulary Expansion','Arjuna and Persuasive Speaking','Srikandi and Presentation Confidence','Bima and Argumentative Reading','Gatotkaca and Heroic Narrative','Kresna and Critical Listening','Dalang Performance Scriptwriting','Intercultural Comparison','Digital Storytelling Project','Academic Reflection Essay','Integrated Wayang Performance','Final Portfolio and Research Passport'];
weeks.forEach((title,i)=>db.materials.push({id:uuid(),week:i+1,title,level:i<4?'A2':i<10?'B1':i<14?'B2':'C1',status:'published',skillMap:['listening','speaking','reading','writing','vocabulary','grammar'],outcomes:[`Explain ${title} in accurate English`,`Perform a Wayang-based task using CEFR-aligned language`,`Submit portfolio evidence for meeting ${i+1}`],listening:{script:`Meeting ${i+1}: Listen to a dalang-style narration about ${title}. Identify main idea, details, moral value, and intercultural message.`,questions:['What is the main issue?','Which character value is shown?','What phrase supports the answer?']},reading:{text:`${title} connects Indonesian Wayang heritage with global English communication. Students read a graded passage, identify cultural symbols, infer meaning, and discuss how the story can be explained to an international audience.`,tasks:['Find three key terms','Summarize in 80 words','Identify one intercultural value']},speaking:{prompt:`Record a 90-second dalang narration about ${title}. Use clear stress, rhythm, and audience-oriented explanation.`,rubric:['fluency','pronunciation','organization','cultural clarity']},writing:{prompt:`Write a 180-word reflection on ${title} and its relevance for modern EFL learners.`,rubric:['thesis','coherence','grammar','vocabulary','reflection']},vocabulary:['heritage','narration','wisdom','identity','performance','intercultural'],quiz:[{q:'Wayang-based EFL learning integrates culture and language.',type:'truefalse',answer:'true'},{q:'Mention one skill practiced in this meeting.',type:'short',answer:'speaking'}],portfolio:`Upload audio, written reflection, quiz score, and self-reflection for meeting ${i+1}.`,createdAt:new Date().toISOString()}));
['Quiz','Speaking Performance','Writing Portfolio','Listening Test','Reading Test','Final Performance'].forEach((type,idx)=>db.assessments.push({id:uuid(),title:`${type} Assessment`,type,level:idx<2?'B1':'B2',indicators:['accuracy','fluency','coherence','cultural explanation'],rubric:{excellent:90,good:80,satisfactory:70,needsSupport:60},items:[{q:`Sample ${type} item`,skill:type.split(' ')[0].toLowerCase(),points:10}],status:'active'}));
db.rooms.push({id:uuid(),title:'Open Dalang Studio Room',meetingNo:1,level:'B1',joinLink:'https://meet.jit.si/WayangLinguaNusantara-DalangStudio',agenda:['Opening','Listening task','Breakout discussion','Speaking performance'],chat:[],breakouts:['Semar Group','Srikandi Group'],attendance:[],notes:'No approval required. Students join directly.'}); }
seed();
function sign(user){return jwt.sign({id:user.id,role:user.role,email:user.email,name:user.name},JWT_SECRET,{expiresIn:'8h'});} function auth(req,res,next){const h=req.headers.authorization||''; const t=h.startsWith('Bearer ')?h.slice(7):null; if(!t)return res.status(401).json({error:'Missing token'}); try{req.user=jwt.verify(t,JWT_SECRET); next();}catch(e){res.status(401).json({error:'Invalid token'});} } function requireRole(...rs){return (req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'});} function audit(action,userId,payload){db.reports.push({id:uuid(),action,userId,payload,at:new Date().toISOString()});}
app.get('/api/health',(req,res)=>res.json({ok:true,systems:['auth','lms','assessment','ai-tutor','classroom','analytics','certificate','research-passport']}));
app.post('/api/auth/register',async(req,res)=>{const {name,email,password,role='STUDENT',institution=''}=req.body; if(!email||!password||!name)return res.status(400).json({error:'name,email,password required'}); if(!roles.includes(role))return res.status(400).json({error:'invalid role'}); if(db.users.some(u=>u.email===email))return res.status(409).json({error:'email exists'}); const user={id:uuid(),name,email,passwordHash:await bcrypt.hash(password,10),role,institution,avatar:'',createdAt:new Date().toISOString()}; db.users.push(user); res.json({token:sign(user),user:{...user,passwordHash:undefined}});});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body; const user=db.users.find(u=>u.email===email); if(!user||!await bcrypt.compare(password,user.passwordHash))return res.status(401).json({error:'Invalid credentials'}); res.json({token:sign(user),user:{...user,passwordHash:undefined}});});
app.get('/api/users/me',auth,(req,res)=>{const u=db.users.find(x=>x.id===req.user.id); res.json({...u,passwordHash:undefined});});
app.put('/api/users/me',auth,upload.single('avatar'),(req,res)=>{const u=db.users.find(x=>x.id===req.user.id); Object.assign(u,req.body); if(req.file)u.avatar=`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`; res.json({...u,passwordHash:undefined});});
app.get('/api/users',auth,requireRole('ADMIN'),(req,res)=>res.json(db.users.map(u=>({...u,passwordHash:undefined}))));
app.get('/api/materials',auth,(req,res)=>res.json(db.materials)); app.get('/api/materials/:id',auth,(req,res)=>res.json(db.materials.find(m=>m.id===req.params.id)||{})); app.post('/api/materials',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const m={id:uuid(),...req.body,status:req.body.status||'draft',createdBy:req.user.id,createdAt:new Date().toISOString()}; db.materials.push(m); audit('material:create',req.user.id,{id:m.id}); res.json(m);}); app.put('/api/materials/:id',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const m=db.materials.find(x=>x.id===req.params.id); if(!m)return res.status(404).json({error:'not found'}); Object.assign(m,req.body, {updatedAt:new Date().toISOString()}); res.json(m);}); app.delete('/api/materials/:id',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{db.materials=db.materials.filter(x=>x.id!==req.params.id); res.json({ok:true});});
app.get('/api/assessments',auth,(req,res)=>res.json(db.assessments)); app.post('/api/assessments',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const a={id:uuid(),...req.body,createdBy:req.user.id,createdAt:new Date().toISOString()}; db.assessments.push(a); res.json(a);}); app.post('/api/submissions',auth,upload.single('evidence'),(req,res)=>{const s={id:uuid(),userId:req.user.id,...req.body,file:req.file?req.file.originalname:null,createdAt:new Date().toISOString()}; db.submissions.push(s); res.json(s);}); app.post('/api/scores',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const sc={id:uuid(),...req.body,scoredBy:req.user.id,createdAt:new Date().toISOString()}; db.scores.push(sc); res.json(sc);});
const tutors={Semar:'Reflective academic mentor: clarity, wisdom, structure.',Gareng:'Grammar coach: accuracy, tenses, articles, sentence repair.',Petruk:'Pronunciation coach: stress, rhythm, intelligibility.',Bagong:'Vocabulary coach: word choice, collocation, academic vocabulary.',Dalang:'Storytelling mentor: performance, audience, narrative flow.',Arjuna:'Speaking confidence coach.',Srikandi:'Presentation and leadership coach.',Bima:'Argumentation and critical thinking coach.',Gatotkaca:'Narrative heroism and expressive fluency coach.',Kresna:'Strategic intercultural communication coach.'};
app.get('/api/ai/tutors',auth,(req,res)=>res.json(Object.entries(tutors).map(([name,persona],i)=>({id:name.toLowerCase(),name,persona,portrait:`/assets/tutors/${name.toLowerCase()}.svg`})))); app.post('/api/ai/respond',auth,(req,res)=>{const {tutor='Semar',message=''}=req.body; const persona=tutors[tutor]||tutors.Semar; const words=message.trim().split(/\s+/).filter(Boolean); const response=`${tutor} Response — ${persona}\n\nStrength: Your text contains ${words.length} words and shows an attempt to communicate meaning.\nRevision Focus: ${tutor==='Gareng'?'Check verb tense, articles, and sentence boundaries.':tutor==='Petruk'?'Practice word stress, intonation, and pause groups.':tutor==='Bagong'?'Replace repeated words with stronger academic vocabulary.':tutor==='Semar'?'Clarify your thesis and connect ideas with reflective transitions.':'Organize your idea for audience, evidence, and cultural clarity.'}\nImproved Model: ${message?message.slice(0,220):'Write your draft or speaking script here.'}\nNext Task: Revise, listen to this feedback, then save it to your portfolio.`; const log={id:uuid(),userId:req.user.id,tutor,message,response,createdAt:new Date().toISOString()}; db.aiLogs.push(log); res.json(log);});
app.get('/api/rooms',auth,(req,res)=>res.json(db.rooms)); app.post('/api/rooms',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const r={id:uuid(),chat:[],attendance:[],breakouts:[],...req.body,createdBy:req.user.id,createdAt:new Date().toISOString()}; db.rooms.push(r); res.json(r);}); app.put('/api/rooms/:id',auth,requireRole('ADMIN','LECTURER'),(req,res)=>{const r=db.rooms.find(x=>x.id===req.params.id); if(!r)return res.status(404).json({error:'not found'}); Object.assign(r,req.body); res.json(r);}); app.post('/api/rooms/:id/join',auth,(req,res)=>{const r=db.rooms.find(x=>x.id===req.params.id); if(!r)return res.status(404).json({error:'not found'}); if(!r.attendance.find(a=>a.userId===req.user.id))r.attendance.push({userId:req.user.id,name:req.user.name,joinedAt:new Date().toISOString()}); res.json({ok:true,room:r});}); app.post('/api/rooms/:id/chat',auth,(req,res)=>{const r=db.rooms.find(x=>x.id===req.params.id); const c={id:uuid(),userId:req.user.id,name:req.user.name,text:req.body.text,at:new Date().toISOString()}; r.chat.push(c); res.json(c);});
app.get('/api/analytics/overview',auth,(req,res)=>{const userId=req.user.role==='STUDENT'?req.user.id:req.query.userId; const data={role:req.user.role,materials:db.materials.length,submissions:userId?db.submissions.filter(s=>s.userId===userId).length:db.submissions.length,aiLogs:userId?db.aiLogs.filter(l=>l.userId===userId).length:db.aiLogs.length,rooms:db.rooms.length,attendance:userId?db.rooms.reduce((n,r)=>n+r.attendance.filter(a=>a.userId===userId).length,0):db.rooms.reduce((n,r)=>n+r.attendance.length,0),scores:userId?db.scores.filter(s=>s.userId===userId):db.scores,cefrGrowth:{pre:'A2',current:'B1+',target:'B2'},skillGrowth:{listening:0,speaking:0,reading:0,writing:0}}; res.json(data);});
app.post('/api/certificates',auth,requireRole('ADMIN','LECTURER'),async(req,res)=>{const id=`WLN-${new Date().getFullYear()}-${String(db.certificates.length+1).padStart(4,'0')}`; const verifyUrl=`${req.protocol}://${req.get('host')}/verify/${id}`; const qr=await QRCode.toDataURL(verifyUrl); const cert={id:uuid(),certificateNo:id,verifyUrl,qr,...req.body,issuedBy:req.user.name,issuedAt:new Date().toISOString()}; db.certificates.push(cert); res.json(cert);}); app.get('/api/certificates/verify/:no',(req,res)=>res.json(db.certificates.find(c=>c.certificateNo===req.params.no)||{valid:false}));
app.get('/api/research-passport',auth,(req,res)=>{const uid=req.user.role==='STUDENT'?req.user.id:req.query.userId; res.json({id:`RP-${uid||'ALL'}`,preTest:'A2',postTest:'B1+',evidence:{submissions:db.submissions.filter(s=>!uid||s.userId===uid),aiLogs:db.aiLogs.filter(l=>!uid||l.userId===uid),attendance:db.rooms.flatMap(r=>r.attendance.map(a=>({room:r.title,...a}))).filter(a=>!uid||a.userId===uid)},exportReady:['CSV','SPSS','JSON'],ethics:'De-identified export supported'});});
app.listen(process.env.PORT||4000,()=>console.log(`Wayang Lingua API running on ${process.env.PORT||4000}`));
