CREATE TABLE users (id uuid PRIMARY KEY, name text, email text UNIQUE, password_hash text, role text, cefr_level text, photo_url text, bio text, created_at timestamptz DEFAULT now());
CREATE TABLE courses (id uuid PRIMARY KEY, title text, description text, owner_id uuid REFERENCES users(id));
CREATE TABLE modules (id uuid PRIMARY KEY, course_id uuid REFERENCES courses(id), week int, title text, cefr_level text, outcomes text);
CREATE TABLE module_contents (id uuid PRIMARY KEY, module_id uuid REFERENCES modules(id), skill text, content jsonb);
CREATE TABLE assessments (id uuid PRIMARY KEY, module_id uuid, title text, type text, skill text, level text, prompt text, rubric jsonb, created_by uuid);
CREATE TABLE submissions (id uuid PRIMARY KEY, assessment_id uuid, user_id uuid, content text, file_url text, score numeric, feedback text, created_at timestamptz DEFAULT now());
CREATE TABLE ai_tutor_sessions (id uuid PRIMARY KEY, user_id uuid, tutor text, input text, response text, metrics jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE rooms (id uuid PRIMARY KEY, module_id uuid, title text, link text, agenda text, starts_at timestamptz, created_by uuid);
CREATE TABLE room_attendance (id uuid PRIMARY KEY, room_id uuid, user_id uuid, joined_at timestamptz, duration_minutes int);
CREATE TABLE certificates (id uuid PRIMARY KEY, user_id uuid, course_id uuid, certificate_no text UNIQUE, verification_hash text, score numeric, cefr_level text, issued_at timestamptz);
CREATE TABLE research_passports (id uuid PRIMARY KEY, user_id uuid, course_id uuid, pretest jsonb, posttest jsonb, analytics jsonb, export_url text);